# Generated by Django 4.0 on 2021-12-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'help', 'verbose_name_plural': 'helps'},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
