# Generated by Django 4.0.2 on 2022-02-05 11:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0003_photo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_size_big',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_size_small',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=''),
        ),
    ]
