# Generated by Django 4.0.2 on 2022-02-05 11:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0004_photo_image_size_big_photo_image_size_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_size_big',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_size_small',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos'),
        ),
    ]
