# Generated by Django 3.2.10 on 2022-01-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0004_auto_20220104_1615'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
