# Generated by Django 4.0.2 on 2022-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0007_alter_photo_description_alter_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='future_description',
            field=models.TextField(blank=True, null=True, verbose_name='Future description'),
        ),
        migrations.AddField(
            model_name='photo',
            name='future_image',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Future image'),
        ),
        migrations.AddField(
            model_name='photo',
            name='future_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Future name'),
        ),
    ]
