# Generated by Django 4.0.2 on 2022-02-08 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0008_photo_future_description_photo_future_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
