# Generated by Django 4.0.2 on 2022-02-16 10:05

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0009_photo_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratedPhoto',
            fields=[
            ],
            options={
                'verbose_name': 'Moderated photo',
                'verbose_name_plural': 'Moderated photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('models_module.photo',),
        ),
        migrations.AddField(
            model_name='photo',
            name='mark_as_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('On deletion', 'On deletion')], default=('New', 'New'), max_length=50),
        ),
    ]
