# Generated by Django 3.2.12 on 2022-02-20 15:20

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0010_moderatedphoto_photo_mark_as_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='mark_as_deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('On deletion', 'On deletion')], default='New', max_length=50),
        ),
    ]
