# Generated by Django 3.2.12 on 2022-04-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('models_module', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='owner_type_comments', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
