# Generated by Django 3.2.12 on 2022-04-06 07:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0018_auto_20220406_0926'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('collection', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='owner_type',
        ),
    ]
