# Generated by Django 3.2.12 on 2022-04-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0019_auto_20220406_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner_id',
            new_name='object_id',
        ),
    ]
