# Generated by Django 3.2.12 on 2022-04-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_module', '0020_auto_20220406_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
